version: '3.8'

services:
  # 主应用服务
  app:
    build: .
    ports:
      - "58101:8000"
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/app/src
    volumes:
      # 挂载日志目录
      - ./videos:/app/videos
    restart: unless-stopped
    networks:
      - userproxy-network

networks:
  userproxy-network:
    driver: bridge 